[project]
name = "nqprd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "akshare>=1.16.98",
    "fire>=0.7.0",
    "loguru>=0.7.3",
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "yfinance>=0.2.63",
]
