name: Daily ETF Open Prediction

on:
  schedule:
    # 定时执行：北京时间每日 09:00 （UTC 01:00）
    - cron: '0 1 * * *'
  # 手动触发
  workflow_dispatch: {}
  # 代码更新或 PR 时触发
  push:
    branches: [ main, dev-ci ]
  pull_request:
    branches: [ main ]

jobs:
  predict-and-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fire loguru pandas numpy akshare yfinance
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Run prediction script
        run: |
          python main.py run --source akshare --lookback_days 60 --etf_symbol 159941

      - name: Read result.json
        id: read_result
        run: |
          DATE=$(jq -r '.date' result.json)
          PRED=$(jq -r '.pred_open' result.json)
          echo "date=$DATE" >> $GITHUB_OUTPUT
          echo "pred_open=$PRED" >> $GITHUB_OUTPUT

      # - name: Create or update GitHub Issue
      #   if: |
      #     github.event_name == 'schedule' ||
      #     github.event_name == 'workflow_dispatch' ||
      #     (github.event_name == 'push' && github.ref == 'refs/heads/dev-ci')
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     PREFIX=""
      #     if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/dev-ci" ]; then
      #       PREFIX="test: "
      #     fi
      #     TITLE="$PREFIX${{ steps.read_result.outputs.date }}: 159941 开盘预测"
      #     BODY="**预测结果**：\n\`\`\`json\n$(cat result.json)\n\`\`\`"
      #     EXISTING=$(gh issue list --search "$TITLE" --json number --jq '.[0].number')
      #     if [ "$EXISTING" = "null" ] || [ -z "$EXISTING" ]; then
      #       gh issue create --title "$TITLE" --body "$BODY" --label prediction
      #     else
      #       gh issue comment $EXISTING --body "$BODY"
      #     fi

      - name: Print result to CI log
        # if: |
        #   (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
        #   (github.event_name == 'pull_request' && github.base_ref == 'main')
        run: |
          echo "=== ETF Prediction Result ==="
          cat result.json
